Add option to publish the sbpl footprint plan
ros-planning/navigation_experimental pull request #58
Opened 2022-03-03 15:24 UTC by LotfiZ

Hello folks,

I added the methods already defined in the sbpl_cart_planner to display the plan with the footprint, it can be useful for debugging or tuning purposes. i dont know if its relevant or not ! 

Cheers

2022-03-03 16:22 UTC, mintar requested changes
Thanks for your contribution, this is definitely useful! I've added some requested changes in the comments.

2022-03-03 16:22 UTC, mintar commented on sbpl_lattice_planner/src/sbpl_lattice_planner.cpp
> +    sbpl_plan_footprint_pub_ = private_nh.advertise<visualization_msgs::Marker>("sbpl_plan_footprint_array", 1);
Maybe a shorter name, like "footprint_markers", would be better? It's in the private namespace anyway, so there won't be any name collisions. Also, it's not an array.

2022-03-03 16:22 UTC, mintar commented on sbpl_lattice_planner/src/sbpl_lattice_planner.cpp
> +   ma.lifetime = ros::Duration(2);
2 seconds is a bit short in my opinion. I'd suggest setting the lifetime to "0". That way, the marker stays visible until the next marker is published.

2022-03-03 16:22 UTC, mintar commented on sbpl_lattice_planner/src/sbpl_lattice_planner.cpp
> +
RViz shows the following warning: "Uninitialized quaternion, assuming identity."

To fix it, set `ma.pose.orientation.w = 1.0`.

2022-03-03 16:22 UTC, mintar commented on sbpl_lattice_planner/src/sbpl_lattice_planner.cpp
> +
Please remove these 2 empty lines.

2022-03-03 16:22 UTC, mintar commented on sbpl_lattice_planner/src/sbpl_lattice_planner.cpp
> +
Please remove these 3 empty lines.

2022-03-03 17:14 UTC, LotfiZ commented
I did the requested changes, if i forgot something i'll happy to fix it. Thank you

2022-03-04 12:00 UTC, mintar commented on sbpl_lattice_planner/include/sbpl_lattice_planner/sbpl_lattice_planner.h
> +  std::vector<geometry_msgs::Point> robot_footprint_;
Why is the extra copy `robot_footprint_` necessary? If I see it correctly, we could just re-use `footprint_`, right?

2022-03-04 12:03 UTC, mintar commented on sbpl_lattice_planner/src/sbpl_lattice_planner.cpp
> +#include <tf/transform_broadcaster.h>
I don't think we need to include the `transform_broadcaster` here. Maybe some more specific includes though? I haven't checked.

2022-03-04 12:04 UTC, mintar commented
Thanks for your changes! I only have two more comments before this can be merged (see above).

2022-03-06 04:01 UTC, LotfiZ commented
Hi Martin, sorry for the late, i made the requested changes but i'm not sure about the TF header that i included, if there is a more optimal way, i can change it ! Thank you

2022-03-07 09:17 UTC, mintar approved these changes

2022-03-07 09:28 UTC, merged

2022-03-07 09:28 UTC, mintar commented
Thanks! I've added a few cleanups and merged the PR.